server:
  port: 80
spring:
  application:
    name: consumer-order-consul
    #注册中心地址
  cloud:
    consul:
      host: 192.169.0.11
      port: 8500
      discovery:
        service-name: ${spring.application.name}