server:
  port: 9527
eureka:
  client:
    register-with-eureka: true #注册服务
    fetch-registry: true  #检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群配置 注册到多个注册中心
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route 路由的ID 没有固定规则但要求唯一,建议配合服务名
          uri: http://localhost:8002  #匹配后提供服务的路由地址
          predicates:
            - Path=/getOne/**  #断言,路径相匹配的进行路由
        - id: payment_routh2
          uri: http://localhost:8002
          predicates:
            - Path=/payment/Lb/**
