server:
  port: 80
spring:
  application:
    name: consumer-order-service
eureka:
  client:
    register-with-eureka: true #注册服务
    fetch-registry: true  #检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群配置 注册到多个注册中心
