server:
  port: 8004
spring:
  application:
    name: cloud-provider-consol-service
    #注册中心地址
  cloud:
    consul:
      host: 192.169.0.11
      port: 8500
      discovery:
        service-name: ${spring.application.name}